
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
     - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-net

  nest:
    restart: always
    container_name: nest
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - .env
    volumes:
      - ../project:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - shared-net
    
  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    networks:
      - shared-net


volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../my-data

networks:
  shared-net:
    name: my_shared_network
    driver: bridge